services:
  api:
    build: .

  db:
    image: postgres:12.7
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=7mJQoyplpNWAEl7C8V6nd4gHHtguSkCG4BF2P2lu"
      - "POSTGRES_DB=birthday"
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:

